### ISSUE TITLE
Hide scroll bar for Steemitpond, ISS Stream, Whale Sonar

### ISSUE THREAD

**Issue by techtek** [techtek/steempi#20]
When loading those external websites displayed in the main menu, a scrollbar is visible next to the content of those website (but it is not needed there, because the external websites scale nicely)

Its a small issue but will improve the look and feel of these features.

(On other external sources the scrollbar need to be visible because of the pages being long)

**Comment by dehenne** [comment]
I never had a scrollbar, so i made a blind fix.
can you please test if the fix helped?
