### ISSUE TITLE
Design a new icon set for the main menu items

### ISSUE THREAD

**Issue by techtek** [techtek/steempi#23]
Design a new icon set for the main menu items

![image](https://user-images.githubusercontent.com/12238251/29998451-d97e2fce-905d-11e7-9d0a-2565799a8b62.png)

**Comment by dehenne** [comment]
At the moment is use font awesome, it was easier for me :D

**Comment by dehenne** [comment]
If you want to insert svg or images, i should extend the API. I assign the bug temporary to me.

**Comment by dehenne** [comment]
You can know use icons the menu ;-)

**Comment by dehenne** [comment]
I include the new icons ;-)
