### ISSUE TITLE
Add a "Test LED button" to settings

### ISSUE THREAD

**Issue by techtek** [techtek/steempi#24]
A setting to test the LED light 

On / Off

Test Notification Leds
- "Test Blue LED" Button
- "Test Green LED" Button
- "Test purple LED" Button

Toggle image button would be the most nice, each LED button in the colour of the LED .

Example
![image](https://user-images.githubusercontent.com/12238251/29998573-57f214a8-9061-11e7-9445-f3da47066292.png)

Example code

```
<?php
$status = array ( 0 );
//set pins mode to output
for ($i = 0; $i <= 7; $i++ ) {
     system ( "gpio mode ".$i." out" );
}
//turns on the LEDs
for ($i = 0; $i <= 7; $i++ ) {
     system ( "gpio write ".$i." 1" );
}
//reads and prints the LEDs status
for ($i = 0; $i <= 7; $i++ ) {
     exec ( "gpio read ".$i, $status );
     echo ( $status[0] );
}
//waits 2 seconds
sleep ( 2 );
//turns off the LEDs
for ($i = 0; $i <= 7; $i++ ) {
     system ( "gpio write ".$i." 0" );
}
?>
```

: http://www.instructables.com/id/Simple-and-intuitive-web-interface-for-your-Raspbe/

**Comment by dehenne** [comment]
Very good idea. I write a GPIO Wrapper, so we can send it with scripts, too.
Added to the Milestone 2

👍

**Comment by dehenne** [comment]
GPIO PHP Wrapper is implemented now.
