### ISSUE TITLE
Change webinterface title / slogan 

### ISSUE THREAD

**Issue by techtek** [techtek/steempi#36]
We need to find the best slogan / title `<title>for the SteemPi webinterface</title>`

Ideas: 

SteemPi | Home

SteemPi | Tv-Box 

SteemPi | Steemit Tv-Box 

SteemPi | Steemit Smart Tv 

SteemPi | Tv-Box and Digital assistant

SteemPi | Your Steemit Tv-Box 

SteemPi | Interface

SteemPi | Steemit, Crypto, Entertainment and more!

SteemPi | Steemit, Digital assistant, Home automation, Entertainment and more!

SteemPi | Connecting your living room with the blockchain

SteemPi | Intelligent personal assistant for your Tv and mobile devices

SteemPi, Digital living room assistant 

SteemPi |  intelligent personal assistant 

SteemPi, The digital assistant that connects to your Tv and Steemit!

STEEMPI

SteemPi

**Comment by dehenne** [comment]
I would use `SteemPi | Tv-Box`
